version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: malik
      POSTGRES_PASSWORD: fysspasswordpostgresdb
      POSTGRES_DB: fyss-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  fyss_dev:
    container_name: fyss_dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://malik:fysspasswordpostgresdb@postgres:5432/fyss-postgres?schema=public
    restart: always
    networks:
      - backend
    cpu_count: 1
    mem_limit: '1g'

networks:
  backend:
    driver: bridge

volumes:
  postgres-data:
    driver: local
